/*
===============================================================================
Module Name : alu
===============================================================================

Description:
------------
This module implements the Arithmetic Logic Unit (ALU) for a RISC-V RV32I
processor.

The ALU performs:
    1. Arithmetic operations
    2. Logical operations
    3. Shift operations
    4. Comparison operations for branch instructions

The operation is selected using the 4-bit `Control` signal.

The `Control` signal is generated by the ALU Control Unit using:
    - opcode
    - funct3
    - funct7

fields from the RISC-V instruction.

Additionally, the `branch` signal determines whether the ALU operates in:
    - Normal ALU execution mode
    - Branch comparison mode

Inputs:
-------
    a, b :
        ALU operands

    Control :
        4-bit ALU operation select signal

    branch :
        Enables branch comparison mode

Outputs:
--------
    result :
        ALU operation result

    compare_out :
        Branch comparison result

ALU Control Encoding:
---------------------
    Instruction     funct3     funct7[5]     Control
    ------------------------------------------------
    ADD             000            0         0000
    SUB             000            1         1000
    XOR             100            0         0100
    OR              110            0         0110
    AND             111            0         0111
    SLL             001            0         0001
    SRL             101            0         0101
    SRA             101            1         1101
    SLT             010            0         0010
    SLTU            011            0         0011

Branch Comparison Encoding:
---------------------------
    Branch Type     funct3     Control
    -----------------------------------
    BEQ             000        1000
    BNE             001        1001
    BLT             100        1100
    BGE             101        1101
    BLTU            110        1110
    BGEU            111        1111

Operation Modes:
----------------
    branch = 0 :
        Normal ALU execution mode

    branch = 1 :
        Branch comparison mode

Special Notes:
--------------
    - Signed operations use `$signed()`
    - Shift amount uses lower 5 bits: b[4:0]
    - compare_out is valid only for branch instructions

===============================================================================
*/

`timescale 1ns / 1ps

module alu(
    input  logic [31:0] a, b,          // ALU operands
    input  logic [3:0]  Control,       // ALU operation select
    input  logic        branch,        // Branch mode enable
    output logic [31:0] result,        // ALU result output
    output logic        compare_out    // Branch comparison output
);

    // ------------------------------------------------------------------------
    // ALU Combinational Logic
    // ------------------------------------------------------------------------
    always_comb begin

        // --------------------------------------------------------------------
        // Default Assignments
        // --------------------------------------------------------------------
        result      = 32'd0;
        compare_out = 1'b0;


        // --------------------------------------------------------------------
        // Branch Comparison Mode
        // --------------------------------------------------------------------
        if (branch) begin

            unique case (Control)

                // BEQ : Branch if Equal
                4'b1000: compare_out = (a == b);

                // BNE : Branch if Not Equal
                4'b1001: compare_out = (a != b);

                // BLT : Branch if Less Than (Signed)
                4'b1100: compare_out = ($signed(a) < $signed(b));

                // BGE : Branch if Greater Than or Equal (Signed)
                4'b1101: compare_out = ($signed(a) >= $signed(b));

                // BLTU : Branch if Less Than Unsigned
                4'b1110: compare_out = (a < b);

                // BGEU : Branch if Greater Than or Equal Unsigned
                4'b1111: compare_out = (a >= b);

                // Default Case
                default: compare_out = 1'b0;

            endcase
        end


        // --------------------------------------------------------------------
        // Normal ALU Operation Mode
        // --------------------------------------------------------------------
        else begin

            unique case (Control)

                // ADD
                4'b0000: result = a + b;

                // SUB
                4'b1000: result = a - b;

                // XOR
                4'b0100: result = a ^ b;

                // OR
                4'b0110: result = a | b;

                // AND
                4'b0111: result = a & b;

                // SLL : Shift Left Logical
                4'b0001: result = a << b[4:0];

                // SRL : Shift Right Logical
                4'b0101: result = a >> b[4:0];

                // SRA : Shift Right Arithmetic
                4'b1101: result = $signed(a) >>> b[4:0];

                // SLT : Set Less Than (Signed)
                4'b0010:
                    result = ($signed(a) < $signed(b))
                             ? 32'd1 : 32'd0;

                // SLTU : Set Less Than Unsigned
                4'b0011:
                    result = (a < b)
                             ? 32'd1 : 32'd0;

                // Default Case
                default: result = 32'd0;

            endcase
        end
    end

endmodule