/*
===============================================================================
Module Name : alu_mul_mux
===============================================================================

Description:
------------
This module implements a 2-to-1 multiplexer for selecting the final execution
result in the Execute (EX) stage of a RISC-V datapath.

The module selects between:
    1. ALU result
    2. Multiplier result

The selection is controlled using the `Mul` control signal generated by
the Control Unit.

Purpose:
--------
This mux is used to support:
    - Normal ALU operations
    - Multiplication instructions

Inputs:
-------
    alu_result :
        Result generated by ALU

    mul_result :
        Result generated by Multiplier unit

    Mul :
        Control signal from Control Unit

Outputs:
--------
    exec_result :
        Final execution-stage result

Selection Logic:
----------------
    Mul     exec_result Output
    --------------------------------
     0      alu_result
     1      mul_result

Operation:
----------
    Mul = 0 :
        Normal ALU operation
        → ALU result is selected

    Mul = 1 :
        Multiplication instruction
        → Multiplier result is selected

Special Note:
-------------
    This mux is commonly used in processors supporting:
        - RV32M extension
        - Hardware multiplier integration

===============================================================================
*/

module alu_mul_mux #(
    parameter WIDTH = 32
)(
    input  logic [WIDTH-1:0] alu_result,   // Result from ALU
    input  logic [WIDTH-1:0] mul_result,   // Result from multiplier
    input  logic             Mul,          // Multiplier select control signal
    output logic [WIDTH-1:0] exec_result   // Final execute-stage result
);

    // ------------------------------------------------------------------------
    // Execute Result Selection MUX
    // Selects between ALU and multiplier outputs
    // ------------------------------------------------------------------------
    always_comb begin

        // --------------------------------------------------------------------
        // Multiplication Instruction
        // Select multiplier result
        // --------------------------------------------------------------------
        if (Mul)
            exec_result = mul_result;


        // --------------------------------------------------------------------
        // Normal ALU Operation
        // Select ALU result
        // --------------------------------------------------------------------
        else
            exec_result = alu_result;

    end

endmodule