/*
===============================================================================
Module Name : alu_in1_mux
===============================================================================

Description:
------------
This module implements a 2-to-1 multiplexer for selecting the first input
(`alu_in1`) to the ALU in a RISC-V datapath.

The selection is controlled using the `Lui` control signal.

Purpose:
--------
This mux is mainly used for:
    1. Normal ALU operations
    2. LUI instruction handling

Inputs:
-------
    rs1 :
        Data from source register rs1
        (Output from Register File)

    imm :
        Immediate value generated by Immediate Generator

    Lui :
        Control signal generated by Control Unit

Outputs:
--------
    alu_in1 :
        First operand input to ALU

Selection Logic:
----------------
    Lui     alu_in1 Output
    ------------------------
     0      rs1
     1      imm

Operation:
----------
    Lui = 0 :
        Normal ALU operation
        → Source register value is selected

    Lui = 1 :
        LUI instruction execution
        → Immediate value is selected

Special Note:
-------------
    For LUI instruction:
        - Immediate value is already shifted left by 12 bits
        - ALU second input becomes zero
        - Final ALU output becomes the immediate itself

===============================================================================
*/

module alu_in1_mux #(
    parameter WIDTH = 32
)(
    input  logic [WIDTH-1:0] rs1,      // Source register 1 value
    input  logic [WIDTH-1:0] imm,      // Immediate value
    input  logic             Lui,      // LUI control signal
    output logic [WIDTH-1:0] alu_in1   // First ALU operand
);

    // ------------------------------------------------------------------------
    // ALU Input-1 Selection MUX
    // Selects between rs1 and immediate value
    // ------------------------------------------------------------------------
    always_comb begin

        // --------------------------------------------------------------------
        // LUI Instruction
        // Select immediate value
        // --------------------------------------------------------------------
        if (Lui)
            alu_in1 = imm;

        // --------------------------------------------------------------------
        // Normal ALU Operations
        // Select rs1 register value
        // --------------------------------------------------------------------
        else
            alu_in1 = rs1;

    end

endmodule