/*
===============================================================================
Module Name : alu_in2_mux
===============================================================================

Description:
------------
This module implements a 4-to-1 multiplexer for selecting the second input
(`alu_in2`) to the ALU in a RISC-V datapath.

The selection is controlled using:
    1. Lui
    2. ALUSrc

These two control signals together form a 2-bit select input:

    sel = {Lui, ALUSrc}

Purpose:
--------
This mux is used to support:
    1. R-Type instructions
    2. I-Type instructions
    3. LUI instruction
    4. AUIPC instruction

Inputs:
-------
    rs2 :
        Source register 2 value from Register File

    imm :
        Immediate value from Immediate Generator

    pc :
        Current Program Counter value

    Lui :
        Control signal generated by Control Unit
        Used for LUI/AUIPC instructions

    ALUSrc :
        ALU source select control signal

Outputs:
--------
    alu_in2 :
        Second operand input to ALU

Selection Logic:
----------------
    Lui  ALUSrc   alu_in2 Output
    -----------------------------------------
     0     0      rs2   (R-Type instructions)
     0     1      imm   (I-Type instructions)
     1     0      0     (LUI instruction)
     1     1      pc    (AUIPC instruction)

Operation:
----------
    R-Type Instructions:
        ALU operand-2 ← rs2

    I-Type Instructions:
        ALU operand-2 ← immediate

    LUI Instruction:
        ALU operand-2 ← 0
        Result = immediate value

    AUIPC Instruction:
        ALU operand-2 ← PC
        Result = PC + immediate

Special Notes:
--------------
    - LUI uses:
            alu_in1 = immediate
            alu_in2 = 0

    - AUIPC uses:
            alu_in1 = immediate
            alu_in2 = PC

===============================================================================
*/

module alu_in2_mux #(
    parameter WIDTH = 32
)(
    input  logic [WIDTH-1:0] rs2,      // Source register 2 value
    input  logic [WIDTH-1:0] imm,      // Immediate value
    input  logic [WIDTH-1:0] pc,       // Current Program Counter
    input  logic             Lui,      // LUI/AUIPC control signal
    input  logic             ALUSrc,   // ALU source select signal
    output logic [WIDTH-1:0] alu_in2   // Second ALU operand
);

    // ------------------------------------------------------------------------
    // ALU Input-2 Selection MUX
    // Selects ALU second operand based on {Lui, ALUSrc}
    // ------------------------------------------------------------------------
    always_comb begin

        // Default assignment
        alu_in2 = '0;

        case ({Lui, ALUSrc})

            // ------------------------------------------------------------
            // R-Type Instructions
            // Select rs2 register value
            // ------------------------------------------------------------
            2'b00: alu_in2 = rs2;


            // ------------------------------------------------------------
            // I-Type Instructions
            // Select immediate value
            // ------------------------------------------------------------
            2'b01: alu_in2 = imm;


            // ------------------------------------------------------------
            // LUI Instruction
            // Select zero
            // ------------------------------------------------------------
            2'b10: alu_in2 = '0;


            // ------------------------------------------------------------
            // AUIPC Instruction
            // Select Program Counter value
            // ------------------------------------------------------------
            2'b11: alu_in2 = pc;

        endcase
    end

endmodule